CREATE TABLE `STUDENT` (
	`id` SERIAL,
	`NO` VARCHAR(10) NOT NULL,
	`NAME` VARCHAR(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL,
	`ENT_YEAR` INT(10) DEFAULT NULL,
	`CLASS_NUM` CHAR(3) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL,
	`IS_ATTEND` BOOLEAN DEFAULT NULL,
	`SCHOOL_CD` CHAR(3) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL,
	PRIMARY KEY (`NO`)
) ENGINE=InnoDB;