CREATE TABLE `SCHOOL` (
	`id` SERIAL,
	`CD` CHAR(3) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
	`NAME` VARCHAR(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL,
	PRIMARY KEY (`CD`)
) ENGINE=InnoDB;